"""
Legion Health Sponsorship Case — Excel Workbook Builder
==========================================================

Builds model/legion_sponsorship_model.xlsx, a founder-editable companion to
model.py/scenarios.py/sensitivity.py. All calculation cells use LIVE EXCEL
FORMULAS that reference 01_Assumptions (no hardcoded calculated values), so
a founder can edit any Low/Base/High cell on 01_Assumptions and see every
downstream tab recalculate.

Scope note: the live formula chain in 02-05 references the BASE (column D)
value of each assumption — this is the standard "operating case" financial-
modeling convention and is what "founder edits an assumption and sees
results update" means in practice. Low/High columns remain visible and
editable for audit/context, and are explicitly pulled into the 05_Sensitivity
tornado table (which by construction flexes one assumption's Low/High while
holding all others at Base — the same "hold everything else at base" logic
used in sensitivity.py). Full low/base/high x pathway x model scenario grids
(45 rows) and the full 13-assumption x 15-combo tornado (195 rows) are
generated by scenarios.py/sensitivity.py into outputs.csv/sensitivity_outputs.csv;
this workbook is not a re-implementation of that full grid (that would
require a scenario-selector/macro layer disproportionate to a model shell),
it is the auditable, editable base-case companion, plus one illustrative
tornado (ai_driven pathway x Model D, the base case's only economically
positive combo) built with genuine flexed-value formulas.

Run: python3 build_excel.py
Then: python3 <xlsx-skill>/scripts/recalc.py legion_sponsorship_model.xlsx
"""

import csv
import os

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

HERE = os.path.dirname(os.path.abspath(__file__))
ASSUMPTIONS_CSV = os.path.join(HERE, "assumptions.csv")
OUT_XLSX = os.path.join(HERE, "legion_sponsorship_model.xlsx")

# ---------------------------------------------------------------------------
# Styles (industry-standard financial-model color coding per xlsx skill)
# ---------------------------------------------------------------------------
FONT_NAME = "Arial"
BLUE = Font(name=FONT_NAME, color="0000FF")           # hardcoded/editable inputs
BLACK = Font(name=FONT_NAME, color="000000")          # formulas
GREEN = Font(name=FONT_NAME, color="008000")          # cross-sheet links
BOLD = Font(name=FONT_NAME, bold=True)
BOLD_WHITE = Font(name=FONT_NAME, bold=True, color="FFFFFF")
TITLE = Font(name=FONT_NAME, bold=True, size=14)
SUBTITLE = Font(name=FONT_NAME, italic=True, size=10, color="555555")
HEADER_FILL = PatternFill("solid", start_color="1F4E78")
SECTION_FILL = PatternFill("solid", start_color="D9E1F2")
INPUT_FILL = PatternFill("solid", start_color="FFF2CC")  # yellow-ish: editable
FLAG_FILL = PatternFill("solid", start_color="FCE4D6")   # legal-review flag (Model C)
POS_FILL = PatternFill("solid", start_color="E2EFDA")    # positive north-star highlight
NEG_FILL = PatternFill("solid", start_color="FCE4E4")    # negative north-star highlight
THIN = Side(style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

CUR0 = '$#,##0;($#,##0);"-"'
CUR2 = '$#,##0.00;($#,##0.00);"-"'
PCT1 = '0.0%;(0.0%);"-"'
NUM0 = '#,##0;(#,##0);"-"'


def style_header_row(ws: Worksheet, row: int, ncols: int):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = BOLD_WHITE
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BORDER


def section_title(ws: Worksheet, row: int, text: str, ncols: int = 8):
    ws.cell(row=row, column=1, value=text).font = BOLD
    ws.cell(row=row, column=1).fill = SECTION_FILL
    for c in range(2, ncols + 1):
        ws.cell(row=row, column=c).fill = SECTION_FILL


def autosize(ws: Worksheet, widths: dict):
    for col, w in widths.items():
        ws.column_dimensions[col].width = w


# ---------------------------------------------------------------------------
# Load assumptions.csv, preserving row order -> Excel row map
# ---------------------------------------------------------------------------
def load_assumptions_rows():
    with open(ASSUMPTIONS_CSV, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


ROWS = load_assumptions_rows()
AROW = {r["assumption_id"]: i + 2 for i, r in enumerate(ROWS)}  # row 1 = header


def A(aid, col="D"):
    """Cross-sheet reference to an assumption's Low(C)/Base(D)/High(E) cell."""
    return f"'01_Assumptions'!{col}{AROW[aid]}"


wb = Workbook()

# ===========================================================================
# TAB 1: 01_Assumptions
# ===========================================================================
ws1 = wb.active
ws1.title = "01_Assumptions"
ws1["A1"] = "Legion Health Sponsorship Case — Model Assumptions Ledger"
ws1["A1"].font = TITLE
ws1["A2"] = ("Editable inputs (blue text, yellow fill = Low/Base/High). Live formulas throughout this "
             "workbook reference the BASE column (D) of this sheet. Every row carries a status label — "
             "never presented as confirmed Legion data unless status begins 'legion_'.")
ws1["A2"].font = SUBTITLE
ws1.merge_cells("A2:K2")

headers = ["ID", "Assumption", "Low", "Base", "High", "Unit", "Source", "Confidence",
           "Decision Impact", "Validation Method", "Status"]
HEADER_ROW = 4
for i, h in enumerate(headers, start=1):
    ws1.cell(row=HEADER_ROW, column=i, value=h)
style_header_row(ws1, HEADER_ROW, len(headers))

STATUS_COLORS = {
    "placeholder_unresolved": "FFC7CE",
    "placeholder_external": "FFEB9C",
    "estimated_external": "C6E0B4",
    "awaiting_data": "FFC7CE",
    "awaiting_research": "FFEB9C",
    "set_provisional": "BDD7EE",
    "legion_data": "A9D18E",
    "legion_derived": "9DC3E6",
}

for i, r in enumerate(ROWS):
    sheet_row = HEADER_ROW + 1 + i
    AROW[r["assumption_id"]] = sheet_row  # finalize actual row incl. header offset
    ws1.cell(row=sheet_row, column=1, value=r["assumption_id"]).font = BLACK
    ws1.cell(row=sheet_row, column=2, value=r["assumption"])
    for col_idx, key in ((3, "low"), (4, "base"), (5, "high")):
        cell = ws1.cell(row=sheet_row, column=col_idx, value=float(r[key]))
        cell.font = BLUE
        cell.fill = INPUT_FILL
        cell.number_format = NUM0 if abs(float(r[key])) >= 1000 or float(r[key]) == int(float(r[key])) else "0.00"
        cell.border = BORDER
    ws1.cell(row=sheet_row, column=6, value=r["unit"])
    ws1.cell(row=sheet_row, column=7, value=r["source"]).alignment = Alignment(wrap_text=True, vertical="top")
    ws1.cell(row=sheet_row, column=8, value=r["confidence"])
    ws1.cell(row=sheet_row, column=9, value=r["decision_impact"])
    ws1.cell(row=sheet_row, column=10, value=r["validation_method"])
    status_cell = ws1.cell(row=sheet_row, column=11, value=r["status"])
    status_cell.fill = PatternFill("solid", start_color=STATUS_COLORS.get(r["status"], "FFFFFF"))
    for c in range(1, 12):
        ws1.cell(row=sheet_row, column=c).border = BORDER
        if c in (2, 6, 8, 9, 10, 11):
            ws1.cell(row=sheet_row, column=c).alignment = Alignment(wrap_text=True, vertical="top")

LAST_ASSUMPTION_ROW = HEADER_ROW + len(ROWS)

legend_row = LAST_ASSUMPTION_ROW + 2
ws1.cell(row=legend_row, column=1, value="Status legend:").font = BOLD
legend_text = [
    "placeholder_unresolved / awaiting_data / awaiting_research = no external or Legion source yet; analytic placeholder only.",
    "placeholder_external = PLACEHOLDER pending Legion data, anchored to an external benchmark (see Source column).",
    "estimated_external = sourced to an external comparable (research/comparable_notes.md); not Legion data.",
    "set_provisional = lead-judgment policy lever (e.g., target margin), not an empirical estimate.",
    "legion_data = operating data provided by Legion (data/ceo_data_integration.md).",
    "legion_derived = built from Legion data plus analyst derivation (see A02b notes).",
    "Replace placeholders with Legion actuals as they arrive (see model_readme.md).",
]
for j, t in enumerate(legend_text):
    ws1.cell(row=legend_row + 1 + j, column=1, value="  - " + t).font = SUBTITLE

autosize(ws1, {"A": 8, "B": 42, "C": 11, "D": 11, "E": 11, "F": 20, "G": 46, "H": 12, "I": 12, "J": 22, "K": 22})
ws1.freeze_panes = "A5"

# ===========================================================================
# TAB 2: 02_Unit_Economics
# ===========================================================================
ws2 = wb.create_sheet("02_Unit_Economics")
ws2["A1"] = "Unit Economics — Three Care Pathways"
ws2["A1"].font = TITLE
ws2["A2"] = ("Care-delivery (COGS-only) cost and fully loaded incremental cost per patient per year, by pathway. "
             "All cells reference 01_Assumptions live (Base column unless noted). See model.py for formula source.")
ws2["A2"].font = SUBTITLE
ws2.merge_cells("A2:H2")

PATHWAYS = [
    ("traditional", "Traditional clinician visit", "A01", "A03"),
    ("ai_supported", "AI-supported clinician care", "A02", "A03b"),
    ("ai_driven", "Mostly-AI-driven care episode", "A02b", "A04"),
]

r = 4
section_title(ws2, r, "1. Care-Delivery Cost per Patient per Year (COGS only) — Low / Base / High", 7)
r += 1
hdr = ["Pathway", "Cost/unit assumption", "Units/patient/yr assumption", "Cost — Low", "Cost — Base", "Cost — High", "Formula"]
for i, h in enumerate(hdr, start=1):
    ws2.cell(row=r, column=i, value=h)
style_header_row(ws2, r, len(hdr))
r += 1
PATHWAY_CARE_COST_ROW = {}
for key, label, cost_aid, units_aid in PATHWAYS:
    ws2.cell(row=r, column=1, value=label)
    ws2.cell(row=r, column=2, value=f"{cost_aid} (cost/unit)")
    ws2.cell(row=r, column=3, value=f"{units_aid} (units/yr)")
    for col_idx, col_letter in ((4, "C"), (5, "D"), (6, "E")):
        f = ws2.cell(row=r, column=col_idx, value=f"={A(cost_aid, col_letter)}*{A(units_aid, col_letter)}")
        f.number_format = CUR0
        f.font = GREEN
    ws2.cell(row=r, column=7, value="cost_per_unit x units_per_patient_per_yr").font = SUBTITLE
    PATHWAY_CARE_COST_ROW[key] = r
    for c in range(1, 8):
        ws2.cell(row=r, column=c).border = BORDER
    r += 1

r += 1
section_title(ws2, r, "2. Fully Loaded Incremental Cost per Patient per Year (Base Case) — by Pathway", 9)
r += 1
ws2.cell(row=r, column=1, value=("Note: sponsor-servicing, commercial, and compliance costs are allocated per patient "
                                  "and do not vary by pathway (they depend on sponsor-contract structure and eligible "
                                  "population, A08/A09/A23/A13). Trust-churn cost uses the Model B external-anchor ARPU "
                                  "(A05 Base) as the revenue-at-risk proxy, matching sensitivity.py's break-even solver "
                                  "convention (documented there as a stable approximation since trust cost is a small "
                                  "share of ARPU). Core-Book Contagion (NEW v2, added post model v2 review Attack "
                                  "#5/2.5) is a SECOND, separate trust-cost term netting a placeholder spillover rate "
                                  "(A26) against Legion's EXISTING core fee-for-service revenue per patient (A25), not "
                                  "sponsor-tier ARPU — included in every row, base value deliberately small so it "
                                  "remains visibly provisional."))
ws2.cell(row=r, column=1).font = SUBTITLE
ws2.merge_cells(start_row=r, start_column=1, end_row=r, end_column=9)
r += 1
hdr2 = ["Pathway", "Care Delivery", "Sponsor Servicing", "Commercial (Sales)", "Compliance/Legal",
        "Trust/Churn (Sponsor-Tier)", "Core-Book Contagion (NEW v2)", "Fully Loaded Cost", "Required ARPU @ m=25%"]
for i, h in enumerate(hdr2, start=1):
    ws2.cell(row=r, column=i, value=h)
style_header_row(ws2, r, len(hdr2))
r += 1
FLC_HDR_ROW = r - 1
FLC_ROW = {}
for key, label, cost_aid, units_aid in PATHWAYS:
    care_ref = f"E{PATHWAY_CARE_COST_ROW[key]}"  # column E = "Cost — Base" in the section-1 table
    ws2.cell(row=r, column=1, value=label)
    ws2.cell(row=r, column=2, value=f"={care_ref}").number_format = CUR0
    servicing = f"=0.5*({A('A08')}*{A('A23')})/{A('A13')}"
    ws2.cell(row=r, column=3, value=servicing).number_format = CUR2
    commercial = f"=0.5*({A('A08')}*{A('A23')})/{A('A13')}"
    ws2.cell(row=r, column=4, value=commercial).number_format = CUR2
    compliance = f"={A('A09')}/{A('A13')}"
    ws2.cell(row=r, column=5, value=compliance).number_format = CUR2
    trust = f"={A('A05')}*({A('A10')}+{A('A11')})/100"
    ws2.cell(row=r, column=6, value=trust).number_format = CUR2
    contagion = f"={A('A25')}*{A('A26')}/100"
    ws2.cell(row=r, column=7, value=contagion).number_format = CUR2
    flc = f"=B{r}+C{r}+D{r}+E{r}+F{r}+G{r}"
    ws2.cell(row=r, column=8, value=flc).number_format = CUR0
    req = f"=H{r}/(1-{A('A14')}/100)"
    ws2.cell(row=r, column=9, value=req).number_format = CUR0
    FLC_ROW[key] = r
    for c in range(1, 10):
        cell = ws2.cell(row=r, column=c)
        cell.border = BORDER
        if c >= 2:
            cell.font = BLACK if c != 9 else GREEN
    r += 1

r += 1
section_title(ws2, r, "3. Gross Margin vs. Contribution Margin (illustrative, using Model B external-anchor ARPU)", 8)
r += 1
ws2.cell(row=r, column=1, value=("Gross margin nets out care-delivery COGS only. Contribution margin nets out the FULL "
                                  "loaded cost (care + servicing + commercial + compliance + trust + core-book "
                                  "contagion, NEW v2). Legion's reported ~53% visit gross margin (CEO context, not "
                                  "modeled here) is the narrower measure."))
ws2.cell(row=r, column=1).font = SUBTITLE
ws2.merge_cells(start_row=r, start_column=1, end_row=r, end_column=8)
r += 1
hdr3 = ["Pathway", "Illustrative Revenue (Model B anchor ARPU)", "Care-Delivery Cost", "Gross Margin %",
        "Fully Loaded Cost", "Contribution Margin %", "", ""]
for i, h in enumerate(hdr3, start=1):
    ws2.cell(row=r, column=i, value=h)
style_header_row(ws2, r, 6)
r += 1
for key, label, cost_aid, units_aid in PATHWAYS:
    ws2.cell(row=r, column=1, value=label)
    rev_ref = f"={A('A05')}*{A('A07')}/100"
    ws2.cell(row=r, column=2, value=rev_ref).number_format = CUR2
    ws2.cell(row=r, column=3, value=f"=E{PATHWAY_CARE_COST_ROW[key]}").number_format = CUR0
    ws2.cell(row=r, column=4, value=f"=(B{r}-C{r})/B{r}").number_format = PCT1
    ws2.cell(row=r, column=5, value=f"=H{FLC_ROW[key]}").number_format = CUR0
    ws2.cell(row=r, column=6, value=f"=(B{r}-E{r})/B{r}").number_format = PCT1
    for c in range(1, 7):
        ws2.cell(row=r, column=c).border = BORDER
        if c >= 2:
            ws2.cell(row=r, column=c).font = BLACK
    r += 1

autosize(ws2, {"A": 26, "B": 18, "C": 18, "D": 16, "E": 16, "F": 16, "G": 18, "H": 18, "I": 20})
ws2.freeze_panes = "A4"

# ===========================================================================
# TAB 3: 03_Monetization_Models
# ===========================================================================
ws3 = wb.create_sheet("03_Monetization_Models")
ws3["A1"] = "Monetization Models A-E — Base-Case ARPU and Pathway x Model Grid"
ws3["A1"].font = TITLE
ws3["A2"] = "All formulas reference 01_Assumptions (Base column) live."
ws3["A2"].font = SUBTITLE

r = 4
section_title(ws3, r, "Model A — Programmatic Advertising", 6)
r += 1
ws3.cell(row=r, column=1, value="impressions/patient/yr = sessions x ads/session x fill%")
ws3.cell(row=r, column=1).font = SUBTITLE
r += 1
ws3.cell(row=r, column=1, value="Impressions/patient/yr")
imp_formula = f"={A('A06b')}*{A('A06c')}*{A('A06d')}/100"
ws3.cell(row=r, column=2, value=imp_formula).number_format = NUM0
IMP_ROW = r
r += 1
ws3.cell(row=r, column=1, value="Gross ad revenue/patient/yr (impressions x eCPM/1000)")
ws3.cell(row=r, column=2, value=f"=B{IMP_ROW}*{A('A06')}/1000").number_format = CUR2
GROSS_A_ROW = r
r += 1
ws3.cell(row=r, column=1, value="Net ARPU (Model A) after platform fee")
ws3.cell(row=r, column=2, value=f"=B{GROSS_A_ROW}*(1-{A('A06e')}/100)").number_format = CUR2
ARPU_A_ROW = r
ws3.cell(row=r, column=2).font = GREEN
r += 2

section_title(ws3, r, "Model B — Fixed-Fee Sponsorship", 6)
r += 1
ws3.cell(row=r, column=1, value="Gross ARPU = (sponsors x contract value) / exposed patients  [A23 x A24 / A13]")
ws3.cell(row=r, column=2, value=f"=({A('A23')}*{A('A24')})/{A('A13')}").number_format = CUR2
GROSS_B_ROW = r
r += 1
ws3.cell(row=r, column=1, value="Less: sales+servicing cost per patient  [A08 x A23 / A13]")
ws3.cell(row=r, column=2, value=f"=({A('A08')}*{A('A23')})/{A('A13')}").number_format = CUR2
COST_B_ROW = r
r += 1
ws3.cell(row=r, column=1, value="Net ARPU (formula-derived, cost-allocation cross-check)")
ws3.cell(row=r, column=2, value=f"=B{GROSS_B_ROW}-B{COST_B_ROW}").number_format = CUR2
r += 1
ws3.cell(row=r, column=1, value="External-anchor ARPU (A05) x sponsor renewal rate (A07) — USED IN GRID BELOW")
ws3.cell(row=r, column=2, value=f"={A('A05')}*{A('A07')}/100").number_format = CUR2
ARPU_B_ROW = r
ws3.cell(row=r, column=2).font = GREEN
r += 2

section_title(ws3, r, "Model C — Performance Partnership  [FLAG: legal review required, model only — steering risk]", 6)
r += 1
ws3.cell(row=r, column=1).fill = FLAG_FILL
ws3.cell(row=r, column=1, value="Qualified actions/patient/yr = (action rate % ) x 12 months")
ws3.cell(row=r, column=2, value=f"={A('A19')}/100*12").number_format = "0.00"
ACTIONS_C_ROW = r
r += 1
ws3.cell(row=r, column=1, value="ARPU (Model C) = actions/yr x revenue/action")
ws3.cell(row=r, column=2, value=f"=B{ACTIONS_C_ROW}*{A('A20')}").number_format = CUR2
ARPU_C_ROW = r
ws3.cell(row=r, column=2).font = GREEN
r += 2

section_title(ws3, r, "Model D — Employer/Payer Underwriting", 6)
r += 1
ws3.cell(row=r, column=1, value="PMPM = A15 (USD/patient/yr) / 12")
ws3.cell(row=r, column=2, value=f"={A('A15')}/12").number_format = CUR2
PMPM_D_ROW = r
r += 1
ws3.cell(row=r, column=1, value="ARPU (Model D) = PMPM x 12 x utilization adjustment %")
ws3.cell(row=r, column=2, value=f"=B{PMPM_D_ROW}*12*{A('A21')}/100").number_format = CUR2
ARPU_D_ROW = r
ws3.cell(row=r, column=2).font = GREEN
r += 2

section_title(ws3, r, "Model E — Foundation/Nonprofit Underwriting", 6)
r += 1
ws3.cell(row=r, column=1, value="ARPU (Model E) = grant $/yr / cohort size")
ws3.cell(row=r, column=2, value=f"={A('A16')}/{A('A17')}").number_format = CUR2
ARPU_E_ROW = r
ws3.cell(row=r, column=2).font = GREEN
r += 2

MODEL_ARPU_ROW = {
    "A_programmatic_ads": ARPU_A_ROW,
    "B_fixed_fee_sponsorship_external_anchor": ARPU_B_ROW,
    "C_performance_partnership": ARPU_C_ROW,
    "D_employer_payer_underwriting": ARPU_D_ROW,
    "E_foundation_underwriting": ARPU_E_ROW,
}
MODEL_LABELS = {
    "A_programmatic_ads": "A. Programmatic Ads",
    "B_fixed_fee_sponsorship_external_anchor": "B. Fixed-Fee Sponsorship",
    "C_performance_partnership": "C. Performance Partnership (legal review req'd)",
    "D_employer_payer_underwriting": "D. Employer/Payer Underwriting",
    "E_foundation_underwriting": "E. Foundation Underwriting",
}

section_title(ws3, r, "Base-Case Grid: Pathway x Model — Required vs. Actual ARPU, Gap, North-Star Margin", 12)
r += 1
ws3.cell(row=r, column=1, value=("Reproduces the base-case rows of outputs.csv (scenarios.py) with live formulas. "
                                  "North-star = risk-adjusted contribution margin per eligible patient per year "
                                  "(sponsor revenue - care cost - servicing - commercial - compliance - trust churn "
                                  "- core-book contagion, NEW v2). FIXED (2026-07-08): this grid previously "
                                  "omitted the core-book contagion term from Fully Loaded Cost/North-Star entirely "
                                  "(understating both by A25xA26/100, ~$4.06/patient/yr at the new base case) -- "
                                  "added as its own column below so this tab now matches outputs.csv exactly."))
ws3.cell(row=r, column=1).font = SUBTITLE
ws3.merge_cells(start_row=r, start_column=1, end_row=r, end_column=12)
r += 1
hdrg = ["Pathway", "Model", "Care Delivery Cost", "Sponsor Servicing", "Commercial", "Compliance",
        "Trust/Churn Cost", "Core-Book Contagion (NEW v2)", "Fully Loaded Cost", "Required ARPU (m=25%)",
        "Actual ARPU", "North-Star ($/patient/yr)"]
for i, h in enumerate(hdrg, start=1):
    ws3.cell(row=r, column=i, value=h)
style_header_row(ws3, r, len(hdrg))
r += 1
GRID_START = r
for key, label, cost_aid, units_aid in PATHWAYS:
    for model_key in ["A_programmatic_ads", "B_fixed_fee_sponsorship_external_anchor",
                       "C_performance_partnership", "D_employer_payer_underwriting", "E_foundation_underwriting"]:
        ws3.cell(row=r, column=1, value=label)
        ws3.cell(row=r, column=2, value=MODEL_LABELS[model_key])
        ws3.cell(row=r, column=3, value=f"='02_Unit_Economics'!E{PATHWAY_CARE_COST_ROW[key]}").number_format = CUR0
        ws3.cell(row=r, column=4, value=f"='02_Unit_Economics'!C{FLC_ROW[key]}").number_format = CUR2
        ws3.cell(row=r, column=5, value=f"='02_Unit_Economics'!D{FLC_ROW[key]}").number_format = CUR2
        ws3.cell(row=r, column=6, value=f"='02_Unit_Economics'!E{FLC_ROW[key]}").number_format = CUR2
        arpu_ref = f"B{MODEL_ARPU_ROW[model_key]}"
        ws3.cell(row=r, column=7, value=f"={arpu_ref}*({A('A10')}+{A('A11')})/100").number_format = CUR2
        ws3.cell(row=r, column=8, value=f"='02_Unit_Economics'!G{FLC_ROW[key]}").number_format = CUR2
        ws3.cell(row=r, column=9, value=f"=C{r}+D{r}+E{r}+F{r}+G{r}+H{r}").number_format = CUR0
        ws3.cell(row=r, column=10, value=f"=I{r}/(1-{A('A14')}/100)").number_format = CUR0
        ws3.cell(row=r, column=11, value=f"={arpu_ref}").number_format = CUR2
        ns_cell = ws3.cell(row=r, column=12, value=f"=K{r}-C{r}-D{r}-E{r}-F{r}-G{r}-H{r}")
        ns_cell.number_format = CUR0
        for c in range(1, 13):
            cell = ws3.cell(row=r, column=c)
            cell.border = BORDER
            if c >= 3:
                cell.font = BLACK
        r += 1
GRID_END = r - 1

# Conditional-style highlight (static, computed at build time from known base case) for readability
import openpyxl.formatting.rule as fr
ws3.conditional_formatting.add(
    f"L{GRID_START}:L{GRID_END}",
    fr.CellIsRule(operator="lessThan", formula=["0"], fill=NEG_FILL)
)
ws3.conditional_formatting.add(
    f"L{GRID_START}:L{GRID_END}",
    fr.CellIsRule(operator="greaterThanOrEqual", formula=["0"], fill=POS_FILL)
)

autosize(ws3, {"A": 24, "B": 30, "C": 16, "D": 15, "E": 13, "F": 13, "G": 14, "H": 16, "I": 15, "J": 17, "K": 13, "L": 18})
ws3.freeze_panes = "A5"

# ===========================================================================
# TAB 4: 04_Path_to_1B
# ===========================================================================
ws4 = wb.create_sheet("04_Path_to_1B")
ws4["A1"] = "Valuation Backsolve — Path to a ~$1B Valuation"
ws4["A1"].font = TITLE
ws4["A2"] = "required_revenue = target_valuation / revenue_multiple;  required_patients = required_revenue / ARPU"
ws4["A2"].font = SUBTITLE

r = 4
ws4.cell(row=r, column=1, value="Target valuation (USD)")
ws4.cell(row=r, column=2, value=1_000_000_000).number_format = CUR0
ws4.cell(row=r, column=2).font = BLUE
ws4.cell(row=r, column=2).fill = INPUT_FILL
TV_CELL = f"$B${r}"
r += 2

section_title(ws4, r, "Required Revenue at Each Revenue Multiple", 6)
r += 1
hdr = ["Multiple (x revenue)", "Required Annual Revenue"]
for i, h in enumerate(hdr, start=1):
    ws4.cell(row=r, column=i, value=h)
style_header_row(ws4, r, 2)
r += 1
MULT_ROWS = {}
for mult in (5, 10, 15, 20):
    ws4.cell(row=r, column=1, value=f"{mult}x").font = BLACK
    ws4.cell(row=r, column=2, value=f"={TV_CELL}/{mult}").number_format = CUR0
    MULT_ROWS[mult] = r
    for c in (1, 2):
        ws4.cell(row=r, column=c).border = BORDER
    r += 1
r += 1

section_title(ws4, r, "Required Active Patients by Model (Base-Case ARPU) and Multiple", 8)
r += 1
hdr2 = ["Model", "Base ARPU (USD/patient/yr)"] + [f"Req'd Patients @ {m}x" for m in (5, 10, 15, 20)]
for i, h in enumerate(hdr2, start=1):
    ws4.cell(row=r, column=i, value=h)
style_header_row(ws4, r, len(hdr2))
r += 1
for model_key in ["A_programmatic_ads", "B_fixed_fee_sponsorship_external_anchor",
                   "C_performance_partnership", "D_employer_payer_underwriting", "E_foundation_underwriting"]:
    ws4.cell(row=r, column=1, value=MODEL_LABELS[model_key])
    arpu_ref = f"='03_Monetization_Models'!B{MODEL_ARPU_ROW[model_key]}"
    ws4.cell(row=r, column=2, value=arpu_ref).number_format = CUR2
    for j, mult in enumerate((5, 10, 15, 20)):
        col = 3 + j
        f = f"=IF(B{r}<=0,\"n/a (non-positive ARPU)\",B{MULT_ROWS[mult]}/B{r})"
        ws4.cell(row=r, column=col, value=f).number_format = NUM0
    for c in range(1, 7):
        ws4.cell(row=r, column=c).border = BORDER
    r += 1
r += 1

section_title(ws4, r, "Model B — Required Sponsor Count and Implied Concentration (equal-weight contracts)", 8)
r += 1
ws4.cell(row=r, column=1, value=("Uses A24 (reference annual contract value) as the per-sponsor contract size. "
                                  "concentration_pct_per_sponsor = 1 / required_sponsors (equal-weight assumption)."))
ws4.cell(row=r, column=1).font = SUBTITLE
ws4.merge_cells(start_row=r, start_column=1, end_row=r, end_column=8)
r += 1
hdr3 = ["Multiple", "Required Revenue", "Reference Contract Value (A24)", "Required Sponsors", "Concentration % / Sponsor"]
for i, h in enumerate(hdr3, start=1):
    ws4.cell(row=r, column=i, value=h)
style_header_row(ws4, r, len(hdr3))
r += 1
for mult in (5, 10, 15, 20):
    ws4.cell(row=r, column=1, value=f"{mult}x")
    ws4.cell(row=r, column=2, value=f"=B{MULT_ROWS[mult]}").number_format = CUR0
    ws4.cell(row=r, column=3, value=f"={A('A24')}").number_format = CUR0
    ws4.cell(row=r, column=4, value=f"=B{r}/C{r}").number_format = NUM0
    ws4.cell(row=r, column=5, value=f"=1/D{r}").number_format = PCT1
    for c in range(1, 6):
        ws4.cell(row=r, column=c).border = BORDER
    r += 1

autosize(ws4, {"A": 26, "B": 22, "C": 24, "D": 18, "E": 18, "F": 18, "G": 18})
ws4.freeze_panes = "A4"

# ===========================================================================
# TAB 5: 05_Sensitivity
# ===========================================================================
ws5 = wb.create_sheet("05_Sensitivity")
ws5["A1"] = "Sensitivity — Break-Even Sponsor ARPU and One-Way Tornado"
ws5["A1"].font = TITLE
ws5["A2"] = ("Break-even ARPU table is fully live (all 3 pathways). The tornado table below is illustrative for the "
             "single base-case combo with a positive north-star margin (ai_driven pathway x Model D); it flexes one "
             "assumption to its Low/High value while holding all others at Base, mirroring sensitivity.py's method. "
             "The full 195-row tornado (all 3 pathways x 5 models x 13 assumptions) is in sensitivity_outputs.csv.")
ws5["A2"].font = SUBTITLE
ws5.merge_cells("A2:H2")

r = 4
section_title(ws5, r, "Break-Even Sponsor ARPU per Pathway (Base-Case Cost)", 8)
r += 1
hdr = ["Pathway", "Fully Loaded Cost", "Break-Even ARPU (m=0%)", "Break-Even ARPU (m=20%)",
       "Break-Even ARPU (m=25%)", "Break-Even ARPU (m=30%)", "External Anchor ARPU (A05 Base)",
       "Gap to Anchor @ m=25%"]
for i, h in enumerate(hdr, start=1):
    ws5.cell(row=r, column=i, value=h)
style_header_row(ws5, r, len(hdr))
r += 1
for key, label, cost_aid, units_aid in PATHWAYS:
    ws5.cell(row=r, column=1, value=label)
    ws5.cell(row=r, column=2, value=f"='02_Unit_Economics'!H{FLC_ROW[key]}").number_format = CUR0
    ws5.cell(row=r, column=3, value=f"=B{r}/(1-0)").number_format = CUR0
    ws5.cell(row=r, column=4, value=f"=B{r}/(1-0.20)").number_format = CUR0
    ws5.cell(row=r, column=5, value=f"=B{r}/(1-0.25)").number_format = CUR0
    ws5.cell(row=r, column=6, value=f"=B{r}/(1-0.30)").number_format = CUR0
    ws5.cell(row=r, column=7, value=f"={A('A05')}").number_format = CUR2
    ws5.cell(row=r, column=8, value=f"=G{r}-E{r}").number_format = CUR0
    for c in range(1, 9):
        ws5.cell(row=r, column=c).border = BORDER
        if c >= 2:
            ws5.cell(row=r, column=c).font = BLACK
    r += 1
r += 1

section_title(ws5, r, "Illustrative One-Way Tornado — ai_driven Pathway x Model D (Employer/Payer Underwriting)", 6)
r += 1
ws5.cell(row=r, column=1, value="Base-case north-star margin for this combo:")
ws5.cell(row=r, column=2, value="='03_Monetization_Models'!L" + str(
    GRID_START + PATHWAYS.index(("ai_driven", "Mostly-AI-driven care episode", "A02b", "A04")) * 5 + 3
)).number_format = CUR0
BASE_NS_CELL = f"B{r}"
r += 1

hdrt = ["Assumption Flexed", "North-Star @ Low", "North-Star @ High", "Swing (abs $)"]
for i, h in enumerate(hdrt, start=1):
    ws5.cell(row=r, column=i, value=h)
style_header_row(ws5, r, len(hdrt))
r += 1


def ns_formula_ai_driven_D(override_aid=None, override_col="D"):
    """
    Build the north-star formula for pathway=ai_driven, model=D, with one
    assumption's column swapped to override_col (C=Low or E=High); all
    others held at Base (D). Mirrors sensitivity.py's
    run_base_case_for_pathway_model(pathway='ai_driven', model_key='D...'),
    INCLUDING the core-book contagion term (A25 x A26/100, NEW v2) --
    fixed (2026-07-08) to include this term, which the illustrative
    tornado formula had omitted since the v2 core-book-contagion term was
    added (a pre-existing gap vs. sensitivity.py, not a Phase-5-introduced
    change; it does not affect the swing values for the assumptions
    actually flexed here, since A25/A26 are not among TORNADO_AIDS below,
    but it DID understate every North-Star @ Low/High cell by a constant
    ~$4.06/patient/yr at the new base case).
    """
    def c(aid):
        return override_col if aid == override_aid else "D"

    care_cost = f"({A('A02b', c('A02b'))}*{A('A04', c('A04'))})"
    servicing = f"(0.5*({A('A08', c('A08'))}*{A('A23', c('A23'))})/{A('A13', c('A13'))})"
    commercial = f"(0.5*({A('A08', c('A08'))}*{A('A23', c('A23'))})/{A('A13', c('A13'))})"
    compliance = f"({A('A09', c('A09'))}/{A('A13', c('A13'))})"
    pmpm = f"({A('A15', c('A15'))}/12)"
    util = f"({A('A21', c('A21'))}/100)"
    arpu_d = f"({pmpm}*12*{util})"
    trust = f"({arpu_d}*({A('A10', c('A10'))}+{A('A11', c('A11'))})/100)"
    contagion = f"({A('A25', c('A25'))}*{A('A26', c('A26'))}/100)"
    return f"={arpu_d}-{care_cost}-{servicing}-{commercial}-{compliance}-{trust}-{contagion}"


TORNADO_AIDS = [
    ("A15", "Sponsor ARPU - employer PEPM rate (Model D anchor)"),
    ("A02b", "Care cost - AI-driven episode"),
    ("A21", "Engagement - employer utilization adjustment"),
    ("A11", "Trust churn - retention loss"),
    ("A13", "Eligible patient volume"),
    ("A10", "Trust churn - booking conversion loss"),
    ("A08", "Sales/servicing cost per contract"),
    ("A09", "Compliance/legal cost"),
]
TORNADO_START = r
for aid, label in TORNADO_AIDS:
    ws5.cell(row=r, column=1, value=f"{aid}: {label}")
    ws5.cell(row=r, column=2, value=ns_formula_ai_driven_D(aid, "C")).number_format = CUR0
    ws5.cell(row=r, column=3, value=ns_formula_ai_driven_D(aid, "E")).number_format = CUR0
    ws5.cell(row=r, column=4, value=f"=ABS(C{r}-B{r})").number_format = CUR0
    for c in range(1, 5):
        ws5.cell(row=r, column=c).border = BORDER
        if c >= 2:
            ws5.cell(row=r, column=c).font = BLACK
    r += 1
TORNADO_END = r - 1

r += 1
ws5.cell(row=r, column=1, value=("Rank by Swing (abs $) column D above to identify dominant assumptions for this combo "
                                  "(largest swing = most decision-relevant to validate first)."))
ws5.cell(row=r, column=1).font = SUBTITLE
ws5.merge_cells(start_row=r, start_column=1, end_row=r, end_column=6)

autosize(ws5, {"A": 40, "B": 18, "C": 18, "D": 16, "E": 18, "F": 18, "G": 20, "H": 18})
ws5.freeze_panes = "A4"

# ===========================================================================
# TAB 6: 06_Sources
# ===========================================================================
ws6 = wb.create_sheet("06_Sources")
ws6["A1"] = "Sources & Provenance"
ws6["A1"].font = TITLE
ws6["A2"] = ("Every quantitative input traces to one of: (1) an external benchmark cited in "
             "research/comparable_notes.md, (2) an explicit analytic placeholder (labeled), or (3) a lead-judgment "
             "policy lever. No cell in this workbook represents confirmed Legion internal data.")
ws6["A2"].font = SUBTITLE
ws6.merge_cells("A2:F2")

r = 4
hdr = ["Assumption ID", "Assumption", "Status", "Source (as recorded in 01_Assumptions)"]
for i, h in enumerate(hdr, start=1):
    ws6.cell(row=r, column=i, value=h)
style_header_row(ws6, r, len(hdr))
r += 1
for row_data in ROWS:
    ws6.cell(row=r, column=1, value=row_data["assumption_id"])
    ws6.cell(row=r, column=2, value=row_data["assumption"]).alignment = Alignment(wrap_text=True)
    ws6.cell(row=r, column=3, value=row_data["status"])
    ws6.cell(row=r, column=4, value=row_data["source"]).alignment = Alignment(wrap_text=True)
    for c in range(1, 5):
        ws6.cell(row=r, column=c).border = BORDER
    r += 1

r += 1
section_title(ws6, r, "Key External Anchors Referenced (see research/comparable_notes.md for full detail)", 4)
r += 1
anchors = [
    "GoodRx pharma-manufacturer-solutions ARPU proxy: ~$15/patient/yr [DERIVED, third-party-sourced] -> A05 base.",
    "Facebook / patient-health-vertical contextual eCPM: $20-45 [Third-party estimate] -> A06 range. Do NOT use physician CPMs ($70-1,000+, OpenEvidence/Doximity) for a patient audience.",
    "Employer/payer PEPM benchmark: EAP $3-9 PEPM ($36-108/yr) to Lyra/Spring Health premium $120-350/mo ($1,440-4,200/yr) [Third-party estimates] -> A15 range.",
    "Pharma agency retainer / CSO contract-size ranges ($5K/mo-$50M) -> A08, A24 order-of-magnitude anchors.",
    "GoodRx FTC Health Breach Notification Rule enforcement (2023) and Cerebral FTC action (2024): regulatory precedent informing A09 compliance-cost high end and the trust-churn framing (A10/A11) — not used to derive a numeric trust-loss estimate (no such benchmark exists; A10/A11 remain placeholder_unresolved pending a patient concept test).",
]
for a in anchors:
    ws6.cell(row=r, column=1, value="- " + a).alignment = Alignment(wrap_text=True)
    ws6.merge_cells(start_row=r, start_column=1, end_row=r, end_column=6)
    ws6.row_dimensions[r].height = 30
    r += 1

autosize(ws6, {"A": 14, "B": 40, "C": 20, "D": 70})
ws6.freeze_panes = "A5"

wb.save(OUT_XLSX)
print(f"Wrote {OUT_XLSX}")
print(f"AROW map has {len(AROW)} entries; last assumption row = {LAST_ASSUMPTION_ROW}")
